Repository wecode-bootcamp-korea/27-2nd-SUULGO-backend, pull requests merged in 2021-12, with the labels that each got.

#1 [CREATED] users앱의 models.py 를 작성
  users/migrations/0001_initial.py
  users/models.py
Labels: Status: 리뷰 요청

#2 [Modify] ManyToManyField 추가 및 alcohol_level 관련 테이블 삭제
  users/migrations/0001_initial.py
  users/models.py
Labels: Status: 리뷰 요청

#10 [ Create ] login decorator 구현하였습니다.
  core/utils.py
Labels: Status: Accepted

#6 [Created] 소셜 로그인 페이지 기능 구현 및 유닛 테스트
  suulgo/urls.py
  users/migrations/0002_alter_survey_alcohol_level.py
  users/models.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: 도움 요청

#5 [ Create ] 리스트페이지 ProductListView
  surveys/urls.py
  surveys/views.py
  suulgo/urls.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#7 [ Create ] 약속요청 기능 PromiseView 구현
  users/migrations/0003_meeting_is_accept.py
  users/models.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#8 [ Create ] 약속요청 알림 기능 PromiseAlarmView 구현
  suulgo/urls.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#12 [MODIFIED] Endpoint 이름 수정 및 코드 간략화
  core/utils.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: Conflict 해결 요청, Status: Accepted

#15 [ modify ] 유저앱 모델 수정하였습니다.
  users/migrations/0004_alter_alcoholcategory_surveys_and_more.py
  users/migrations/0005_alter_survey_user.py
  users/migrations/0006_alter_survey_alcohol_limit_alter_survey_stack.py
  users/models.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#16 [modify] 상세페이지 리펙토링
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#13 [ Create ] matching list 뷰 구현하였습니다. (매칭 알고리즘)
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#17 [CREATED] Survey View (설문조사페이지) 구현
  surveys/tests.py
  surveys/urls.py
  surveys/views.py
  suulgo/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#19 [modify] review내용을 토대로 매칭리스트의 딕셔너리를 int로 수정하였습니다.
  users/views.py
Labels: Status: 리뷰 요청

#20 [ modify ] Survey View (설문조사페이지) 구현
  surveys/views.py
Labels: Status: Accepted

#21 [modify] profile page view 반환값 수정하였습니다.
  users/views.py
Labels: Status: 리뷰 요청

#23 Create README.md
  README.md
Labels: Status: 리뷰 요청
